### ISSUE TITLE
Real Time / No Real Time Display

### ISSUE THREAD

**Issue by simonjenny** [timeforcoffee/timeforcoffee-ios#1]
I would like to suggest, to change the display from realtime (prognosis) departure time data to the within the public transport commonly accepted format by displaying the remaining time in minutes when realtime data is available and displaying the time (HH.mm) itself when realtime data is not available instead of "No Realtime data..."

**Comment by chregu** [comment]
yes, we're not happy with the "no realtime data" thingie. Especially for places where there never is no real time data.

But we already show the "remaining time in minutes" for both cases. I didn't find a proper solution yet, since the information "no real time data" can be useful, if there's real time data most of the tiime

I also think it's helpful to see HH:mm all the time and not only if there's no real time data

But we're open to suggestions
